[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
surf = "4pzvADeMCm62GziZvTfEMTeoYnraQJJmN5tAdqd6ARSM"

[programs.localnet]
surf = "4pzvADeMCm62GziZvTfEMTeoYnraQJJmN5tAdqd6ARSM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tushar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
