[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
surf = "6XKkLh8nS7xQRRfdTfCCaqV9jBTzM7BG6Cyw7t8fhstP"

[programs.devnet]
surf = "6XKkLh8nS7xQRRfdTfCCaqV9jBTzM7BG6Cyw7t8fhstP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
