[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
surf = "A9YHxLTPtT6YSCi793gNFMB4nUTByXhq9DzgKf169Zf"

[programs.localnet]
surf = "A9YHxLTPtT6YSCi793gNFMB4nUTByXhq9DzgKf169Zf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
